# Generated by Django 4.2.4 on 2023-09-05 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0002_alter_user_options_alter_user_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_roles',
            new_name='user_role',
        ),
    ]
